
logging:
  file:
    name: logs/iis-manager.log
  level:
    root: info
    org:
      apache: error
      springframework: error
server:
  port: 1111
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1GB
  security:
    enabled: false
    user:
      name: admin
      password: admin123
